Formatting search output JSON
PathwayCommons/hyper-recent pull request #30
Opened 2023-02-27 19:18 UTC by Suhyma

2023-03-02 17:53 UTC, jvwong approved these changes

2023-03-02 17:53 UTC, jvwong commented on src/cli.js
> +    const formattedRes = res.map(article => ({
This mapping fixes the data input and output schema, making the function less reusable (e.g. what if the input article schema changes such as fetching from another organizations). An alternative is to pass a formatting function.

2023-03-06 19:40 UTC, maxkfranz commented
@Suhyma @jvwong 

There's a conflict in the PR that would need to be addressed in both the PR and @Suhyma's branch going forward.

2023-03-08 17:01 UTC, jvwong requested changes
Great - just wondering about the file open/close.

2023-03-08 18:40 UTC, Suhyma commented on src/data-search.js
> +  const fileHandle = await fs.openSync('example-data/data.json', 'w');
You're right, just removed the extra file open and close.

2023-03-08 19:32 UTC, jvwong approved these changes
Works for me.

2023-03-08 19:33 UTC, merged